# use v2.3 API to allow `mem_limit` option
version: "2.3"

services:
  consul:
    image: consul
    command: agent -server -bootstrap -ui
    hostname: consul-1
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    container_name: consul
    restart: unless-stopped
    volumes:
      - ./volumes/consul:/consul/data
    labels:
      - "SERVICE_IGNORE=yes"
    restart: unless-stopped

  vault:
    container_name: vault
    image: vault:1.0.1
    command: vault server -config=/vault/config
    volumes:
      - ./volumes/vault/config:/vault/config
      - ./volumes/vault/data:/vault/data
      - ./volumes/vault/logs:/vault/logs
      - ./vault_gluu_policy.hcl:/vault/config/policy.hcl
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_REDIRECT_INTERFACE=eth0
      - VAULT_CLUSTER_INTERFACE=eth0
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"consul:8500","path":"vault/"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}}}
    restart: unless-stopped
    depends_on:
      - consul
    labels:
      - "SERVICE_IGNORE=yes"

  registrator:
    image: gluufederation/registrator:dev
    command: registrator -internal -cleanup -resync 30 -retry-attempts 5 -retry-interval 10 consul://consul:8500
    container_name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped
    depends_on:
      - consul

  # redis:
  #   image: redis:alpine
  #   # run cluster-enabled redis-server
  #   # command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --appendonly yes --cluster-node-timeout 5000
  #   container_name: redis
  #   labels:
  #     - "SERVICE_IGNORE=yes"
  #   restart: unless-stopped

  nginx:
    image: gluufederation/nginx:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    restart: unless-stopped
    labels:
      - "SERVICE_IGNORE=yes"
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id

  ldap:
    image: gluufederation/opendj:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_LDAP_INIT=true
      - GLUU_LDAP_INIT_HOST=ldap
      - GLUU_LDAP_INIT_PORT=1636
      - GLUU_OXTRUST_CONFIG_GENERATION=true
      - GLUU_CACHE_TYPE=NATIVE_PERSISTENCE
      # - GLUU_CACHE_TYPE=REDIS  # don't forget to enable redis service
      # - GLUU_REDIS_URL=redis:6379
      # - GLUU_REDIS_TYPE=STANDALONE
      # the value must match service name `ldap` because other containers
      # use this value as LDAP hostname
      - GLUU_CERT_ALT_NAME=ldap
      - GLUU_LDAP_ADVERTISE_ADDR=ldap
      # options: ldap/couchbase/hybrid
      - GLUU_PERSISTENCE_TYPE=ldap
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      # - GLUU_PERSISTENCE_LDAP_MAPPING=default
    container_name: ldap
    volumes:
      - ./volumes/opendj/config:/opt/opendj/config
      - ./volumes/opendj/ldif:/opt/opendj/ldif
      - ./volumes/opendj/logs:/opt/opendj/logs
      - ./volumes/opendj/db:/opt/opendj/db
      - ./volumes/opendj/flag:/flag
      - ./volumes/opendj/backup:/opt/opendj/bak
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      # - ./101-ox.ldif:/opt/opendj/config/schema/101-ox.ldif
    restart: unless-stopped
    labels:
      - "SERVICE_IGNORE=yes"

  oxauth:
    image: gluufederation/oxauth:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      # options: ldap/couchbase/hybrid
      - GLUU_PERSISTENCE_TYPE=ldap
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      - GLUU_PERSISTENCE_LDAP_MAPPING=default
      # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
      - GLUU_LDAP_URL=ldap:1636
      # used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
      - GLUU_COUCHBASE_URL=couchbase
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxauth
    volumes:
      - ./volumes/oxauth/custom/pages:/opt/gluu/jetty/oxauth/custom/pages
      - ./volumes/oxauth/custom/static:/opt/gluu/jetty/oxauth/custom/static
      - ./volumes/oxauth/custom/libs:/opt/gluu/jetty/oxauth/custom/libs
      - ./volumes/oxauth/custom/i18n:/opt/gluu/jetty/oxauth/custom/i18n
      - ./volumes/oxauth/logs:/opt/gluu/jetty/oxauth/logs
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
    mem_limit: 1536M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxauth"
      - "SERVICE_8080_CHECK_HTTP=/oxauth/.well-known/openid-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"

  oxtrust:
    image: gluufederation/oxtrust:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_OXAUTH_BACKEND=oxauth:8080
      # options: ldap/couchbase/hybrid
      - GLUU_PERSISTENCE_TYPE=ldap
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      - GLUU_PERSISTENCE_LDAP_MAPPING=default
      # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
      - GLUU_LDAP_URL=ldap:1636
      # used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
      - GLUU_COUCHBASE_URL=couchbase
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxtrust
    volumes:
      - ./volumes/oxtrust/custom/pages:/opt/gluu/jetty/identity/custom/pages
      - ./volumes/oxtrust/custom/static:/opt/gluu/jetty/identity/custom/static
      - ./volumes/oxtrust/custom/libs:/opt/gluu/jetty/identity/custom/libs
      - ./volumes/oxtrust/custom/i18n:/opt/gluu/jetty/identity/custom/i18n
      - ./volumes/oxtrust/logs:/opt/gluu/jetty/identity/logs
      - ./volumes/shared-shibboleth-idp:/opt/shared-shibboleth-idp
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
    mem_limit: 1536M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxtrust"
      - "SERVICE_8080_CHECK_HTTP=/identity/restv1/scim-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"
      - "APP_NAME=oxtrust"

  oxshibboleth:
    image: gluufederation/oxshibboleth:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      # options: ldap/couchbase/hybrid
      - GLUU_PERSISTENCE_TYPE=ldap
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      - GLUU_PERSISTENCE_LDAP_MAPPING=default
      # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
      - GLUU_LDAP_URL=ldap:1636
      # used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
      - GLUU_COUCHBASE_URL=couchbase
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxshibboleth
    volumes:
      - ./volumes/shared-shibboleth-idp:/opt/shared-shibboleth-idp
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
    mem_limit: 1024M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxshibboleth"
      - "SERVICE_8086_CHECK_HTTP=/idp"
      - "SERVICE_8086_CHECK_INTERVAL=15s"
      - "SERVICE_8086_CHECK_TIMEOUT=5s"

  oxpassport:
    image: gluufederation/oxpassport:4.0.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      # - PASSPORT_LOG_LEVEL=debug
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
    container_name: oxpassport
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxpassport"
      - "SERVICE_8090_CHECK_HTTP=/passport/token"
      - "SERVICE_8090_CHECK_INTERVAL=15s"
      - "SERVICE_8090_CHECK_TIMEOUT=5s"

  # key_rotation:
  #   image: gluufederation/key-rotation:4.0.0_dev
  #   environment:
  #     - GLUU_CONFIG_CONSUL_HOST=consul
  #     - GLUU_SECRET_VAULT_HOST=vault
  #     - GLUU_LDAP_URL=ldap:1636
  #     - GLUU_KEY_ROTATION_INTERVAL=2  # interval to regenerate keys if needed (in hours)
  #     - GLUU_KEY_ROTATION_CHECK=30    # interval to check whether keys should be checked (in seconds)
  #   volumes:
  #     - ./vault_role_id.txt:/etc/certs/vault_role_id
  #     - ./vault_secret_id.txt:/etc/certs/vault_secret_id
  #   container_name: key-rotation
  #   restart: unless-stopped
  #   labels:
  #     - "SERVICE_IGNORE=yes"

  # cr_rotate:
  #   image: gluufederation/cr-rotate:4.0.0_dev
  #   environment:
  #     - GLUU_CONFIG_CONSUL_HOST=consul
  #     - GLUU_SECRET_VAULT_HOST=vault
  #     - GLUU_LDAP_URL=ldap:1636
  #     - GLUU_CR_ROTATION_CHECK=60
  #   volumes:
  #     - ./vault_role_id.txt:/etc/certs/vault_role_id
  #     - ./vault_secret_id.txt:/etc/certs/vault_secret_id
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   container_name: cr-rotate
  #   restart: unless-stopped
  #   labels:
  #     - "SERVICE_IGNORE=yes"

  # couchbase:
  #   image: couchbase:6.0.1
  #   volumes:
  #     - ./volumes/couchbase/var:/opt/couchbase/var
  #     - ./couchbase_chain.pem:/opt/couchbase/var/lib/couchbase/inbox/chain.pem
  #     - ./couchbase_pkey.key:/opt/couchbase/var/lib/couchbase/inbox/pkey.key
  #   container_name: couchbase
  #   restart: unless-stopped
  #   mem_limit: 4096M
  #   labels:
  #     - "SERVICE_IGNORE=yes"
